### ISSUE TITLE
Attach MediaStream to returned Stream from recognizeFile/recognizeMicrophone

### ISSUE THREAD

**Issue by repjarms** [watson-developer-cloud/speech-javascript-sdk#100]
Package version: 0.35.4

Currently, when calling `recognizeFile` or `recognizeMicrophone`, multiple child streams are returned within the response. It would really handy to have a `MediaStream` returned as well, for people who want to do things like visualization or any audio manipulation.

**Comment by germanattanasio** [comment]
@repjarms are you going to add this feature in a PR? 😋

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved.

**Comment by nevrologica** [comment]
I am currently using the wavesurfer microphone plugin and when i initialize it before the call to recognizeMicrophone it gets blocked and i cant see any visualization. If i initilize the wavesurfer microphone plugin after the recognizeMicrophone call, the stream gets blocked. The wavesurfer plugin can be initialized with custom AudioContext, or, it can send back the stream containing the MediaStream it uses, it would be very handy if the recognizeMicrophone function could get attached to the same MediaStream.

**Comment by nevrologica** [comment]
So after digging a bit in the sources i have been able to pass in the custom mediaStream like so:

stream = WatsonSpeech.SpeechToText.recognizeMicrophone(Object.assign(speechToken, {
		model: document.querySelector('#speechModel').value,
		mediaStream: mediaStream,
		outputElement: '#output'
	}));

The option is read and the stream is used. So i have succesfuly fixed the issue where i get two requests to allow my microphone to be used when i tested it on Android devices, i was asked twice because i initialize the MediaStream with wavesurfer.js library first. I have even tried to pass in a custom AudioContext by changing the code to to expose the option.context into MicrophoneStream.

So in this case there is no enhancment to be made to the code regarding this. An example would be nice however to let people know it does this.

Furthermore, i am having problems trying to use the same stream through both wavesurfer.js and this SDK on Safari iOS 13. It will work for wavesurfer.js and not for the Speech2Text stream, or sometimes it works for the Speech2Text and not for wavesurfer.js, but never for both. I am at loss here, i am not sure why it doesn't work for both. You can have a look at a staging application on https://www.xbalance.gr/brainy and test it on an iPhone device, you should see the waveform appearing whenever pressing the click&ask button or sometimes you would see the returned websocket response from your SDK. The javascript code can be seen at https://www.xbalance.gr/brainy/js/application.js.php where the function initMicrophoneVisualizer passes the stream to function initiateSpeechVoiceEngine. I would really love to have this fixed for Safari iOS and i can help patching it if i know what is the problem. FYI i also passed in a custom bufferSize option (1024) equal to the one i am using for waversurfer.js when on Safari iOS.

It's not a websocket issue as i am seeing this playing on its own without the wavesurfer on iOS. There is a blocking issue happening somewhere. because i tried adding a console.log into RecognizeMicrophone to see the actual context option i was sending in but the code never reached the point to execute, i was having it just under the MicrophoneStream initialization.

**Comment by germanattanasio** [comment]
@nevrologica Thanks for your research. Would you be willing to write a PR with a simple example?

I tried xbalance.gr/brainy and it works in Chrome. The waveform looks nice.
I have been thinking that a polyfill may catch some of the cross-browser issues we have.
Sadly, I don't have time to do the research

**Comment by nevrologica** [comment]
The example above works for latest versions of Firefox, Chrome, Opera in Windows10 and not for IE Edge (lots of javascript rendering issues in general). Does work for native Android mobile device browsers too. Does not work for iOS Safari (13) on iPhone and iPad (it will only work for either one of the implementations that uses the stream).

However even though a polyfill sounds nice in order to catch errors on browsers (most of them), keep in mind that in Safari iOS we cant see the console when developing just using the devices that it renders the javascript too, you gotta have it connected to a Safari on Desktop using a Mac, and not many developers have both, actually the issue i am having only happens in Safari iOS. For example, in order to catch the errors i have to send the error on an html element using jQuery and have it seen on the device i am rendering it too cause i don't own a Mac right now.

Having said that, i can write an example by using one of the generic template html files on the example forlder and use the wavesurfer.js library in order to show how you would pass in another MediaStream to the SDK and send out error outputs on an html element using jQuery for easier debugging an researching.  I am going to post the HTML code of the example once i have it ready in a comment here and you can then merge it into a file on the master branch if you would feel it's OK.

Let me also say that i have seen both of the libraries using one stream simultaneusly on Safari iOS when i initialize the wavesurfer.js microphone through the on 'data' event of the Speech2Text. So i know iPhone devices can share the same buffer of one stream using different libraries, it's not a security type of thing that prevents it embeded in the mobile browser. I would be keen to research more the kind of initialization of the microphone each library does in order to find potential differences, i am thinking that it should be an event that gets overwritten by either of the two and prevents the second from using the same stream. So far, i have actually made it possible to share the same mediaStream, share the same AudioContext, share the same ammount of bufferSize, but none of this fixed it. It's quite mind-boggling so far and not having the right tools to debug it properly drives me crazy. It would be nice to have someone jumping in the team with an iPhone and a Mac that can debug it and see where the error is occuring.

**Comment by nevrologica** [comment]
So, i made the example and you can have a look at it live here https://www.xbalance.gr/brainy/test/

I am attaching the HTML code for this to go on the main trunk under a filename 'microphone-streaming-auto-stop-with-shared-mediastream.html'.

PS: The only difference between the code i am presenting here and the live on is the backend token API, the live example uses a custom implementation i made in php, other than that, the code should be find to run and added in the main trunk if you feel it's okey, you can grab the wavesurfer included libraries from the live example too.

Now the issue is the following, it works for Chrome,Firefox,Opera in Windows and i suppose it does on Linux too. It works for Android mobile devices. It doesn't work for iOS or iPadOs. You can check the live url with an iPhone and see that it only works for the waveform. So we got the testing environment ready to do some research on the Safari iOS issue i am describing.

Let me know if there is anything else i can provide to fix this.

```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Watson Speech to Text client example</title>
  <link rel="stylesheet" href="style.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div class="container">
<a href="/">&laquo; Examples</a>

<section>
    <h2>Transcribe from Microphone</h2>
    <button id="button">Start Microphone Transcription</button>

    <h2>Output:</h2>
	<div id="waveform">Waveform</div>
    <div id="output">Text</div>
</section>

<script src="scripts/wavesurfer/dist/wavesurfer.min.js"></script>
<script src="scripts/wavesurfer/dist/wavesurfer.microphone.min.js"></script>
<script src="scripts/watson-speech/dist/watson-speech.js"></script>
<!-- window.fetch pollyfill for IE/Edge & Older Chrome/FireFox -->
<script src="scripts/fetch/dist/fetch.umd.js"></script>

<h2>Code for this demo:</h2>

<pre><code><script style="display: block;">

var speechToken;
var wavesurfer;

document.querySelector('#button').onclick = function () {
  fetch('/api/speech-to-text/token')
    .then(function(response) {
      return response.json();
    }).then(function (token) {
	  speechToken = token;
	  wavesurfer = initMicrophoneVisualizer();
	  wavesurfer.microphone.start();
    }).catch(function(error) {
      console.log(error);
    });
};

function isSafari(){
	
	return /^((?!chrome|android).)*safari/i.test(navigator.userAgent || '') || /iPad|iPhone|iPod/i.test(navigator.userAgent || '');
}

function initMicrophoneVisualizer(){
	
	if (wavesurfer === undefined) {
		
		var context, processor;
		var bufferSize = 4096;
		
        if(!isSafari())
            barHeight = 2;
		else{
			barHeight = 8;
			bufferSize = 1024;
						
            context = new (window.AudioContext || window.webkitAudioContext)();
            processor = context.createScriptProcessor(bufferSize, 1, 1);
		}
		
		wavesurfer = WaveSurfer.create({
			container           : '#waveform',
			waveColor           : 'red',
			height		        : 100,
			interact            : false,
			cursorWidth         : 0,
			barHeight			: barHeight,
			barRadius 			: 18,
			audioContext		: context || null,
            audioScriptProcessor: processor || null,
			plugins: [
				WaveSurfer.microphone.create({
                    bufferSize: bufferSize,
                    numberOfInputChannels: 1,
                    numberOfOutputChannels: 1,
                    constraints: {
                        video: false,
                        audio: true
					}
                })
			]
		});
		
		console.log('Microphone Initialized');
		
		wavesurfer.microphone.on('deviceReady', function(stream) {
			console.log('Microphone Ready');
			console.log('Wavesurfer Stream: ' + stream.id);
			initiateSpeechVoiceEngine(stream);
		});
		wavesurfer.microphone.on('deviceError', function(code) {
		});
		wavesurfer.on('error', function(e) {
		});
	}
	
	return wavesurfer;
}

function initiateSpeechVoiceEngine(mediaStream) {

	stream = WatsonSpeech.SpeechToText.recognizeMicrophone(Object.assign(speechToken, {
		mediaStream: mediaStream,
		outputElement: '#output'
	}));
	
	console.log('SpeechToText initiliazed');
	
	console.log('API Stream: ' + stream.options.mediaStream.id);

	stream.on('data', function(data) {			
		if(data.results[0] && data.results[0].final) {						
			stream.stop();					
			wavesurfer.microphone.stop();
			console.log('SpeechToText stoped.');
		}
	});
	  
	stream.on('error', function(err) {
		console.log(err);
	});
}
</script></code></pre>

</div>
</body>
</html>```

**Comment by nevrologica** [comment]
Increasing some momentum in digging further, i have instaled VConsole javascript implementation which is a virtual console embeded on the body of the html and allows me to debug on mobile iOS version by seeing the console.log function output and much more (take that apple!).

On my test regarding wavesurfer and this SDK i have concluded that the passed in mediaStream on recognizeMicrophone always gets wrapped and returns a proper value without any error on Safari iOS. However the stream.on('data', function(data) {} never fires back nor the outputElement i specify gets updated. If i remove the wavesurfer library it works fine. If i pass the mediaStream waversurfer library initializes, even though i still get a valid stream back through recognizeMicrophone() it will never update the outputElement or fire events on the stream it returns. Something tells me that there is an asynchronicity regarding the used MediaStream thats gets mangled in two different threads and it never allows sharing on a second thread, But if this would be the case, then i would never been able to see both libraries using the same stream as i did. I have tried starting and stoping the microphone through wavesurfer inside this SDK stream.on('data', function(data) {} and i could see both playing, but this is not a best approach as it initializes the waverform for every returned websocket chunk i get back from the API. Hope this helps further.

**Comment by nevrologica** [comment]
Huston we have a fix!

I finally been able to crack the blocking issue for Safari iOS.

Apparently the mediaStream implementation introduced by the webKit team of Apple for their Safari iOS version suffers some limitations. I was researching online when i stumbled upon this article https://webrtchacks.com/guide-to-safari-webrtc/ that explains some of the intricacies, quite interesting stuff.

First issue was that whenever a new getUserMedia() request was occuring it was killing the existing stream track. So i managed to overcome this by passing in an initialized mediaStream to recognizeMicrophone thus i handled the second getUserMedia function from firing internaly from the SDK implementation twice. This applies to Chrome iOS too and in general all iOS browsers that implement the new MediaStream API.

But, while i was preventing the original stream from being killed by the second getUserMedia() call (remember first call was from wavesurfer.js or in general it can be from whatever else library or custom code implements a new MediaStream), SDK still couldn't apply the stream events it was registering on the same stream. What actually happens is that if a second getUserMedia() call is made the first stream gets muted and there is no way to programaticaly undo this.

So the fix was an easy one, i clone the original stream and pass into the recognizeMicrophone() function the cloned stream, that is actually a brand new unmuted stream while the original is active as well. And voila, it worked like a charm.

Basically what i did was to change the code in the above example i gave from:
 
```wavesurfer.microphone.on('deviceReady', function(stream) {
			console.log('Microphone Ready');
			console.log('Wavesurfer Stream: ' + stream.id);
			initiateSpeechVoiceEngine(stream);
		});```

to 

```wavesurfer.microphone.on('deviceReady', function(stream) {
			console.log('Microphone Ready');
			console.log('Wavesurfer Stream: ' + stream.id);
                        var audioStream = stream.clone();
			initiateSpeechVoiceEngine(audioStream);
		});```

I have also updated the live example code i have staged with the fix here https://www.xbalance.gr/brainy/test/ . 

The article describing the issues for iOS has some more interesting parts for further development of the SDK. My suggestion is to instead having to do the cloning of the stream on our own, that i can be handled by the recongizeStream() internaly whenever a mediaStream parameter is present and to also make sure getUserMedia() is not called again (this it does, but it could be double checked to make sure).

Hope this helps further the use of this SDK to include all iOS devices from now on.

**Comment by nevrologica** [comment]
Regarding the original post of this issue, the returned stream from recognizeMicrophone does return a MediaStream and it's within the options of the object. It also receives one. So i think this can be closed once and if we can have the cloning workaround inside the main branch and/or the example of the two mediastream i gave. Happy coding :)

**Comment by germanattanasio** [comment]
I added the example that @nevrologica wrote as part of https://github.com/watson-developer-cloud/speech-javascript-sdk/pull/159
