### ISSUE TITLE
Examples Failed to Work

### ISSUE THREAD

**Issue by RezaOwliaei** [watson-developer-cloud/speech-javascript-sdk#124]
**Steps to reproduce**
Open [an example](https://watson-speech.mybluemix.net/microphone-streaming.html)
press Start Microphone Transcription button
open developer tools
You'll get the following error:
```
GET https://watson-speech.mybluemix.net/api/speech-to-text/token 500 (Internal Server Error)
document.querySelector.onclick @ microphone-streaming.html:30
```
and this one:
`watson-speech.js:9114 WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&watson-token=Error%20retrieving%20token' failed: HTTP Authentication failed; no valid credentials available`

**Expected behavior**
Workable examples.

### When reporting a bug, please be sure to include the following:  
- [x] Steps to reproduce
- [x] Expected behavior
- [ ] Actual behavior
- [ ] Browser version(s)
- [ ] SDK version

**Comment by dpopp07** [comment]
@RezaOwliaei Thanks for the issue. I identified the problem and posted a fix with #125 

It should deploy once merged to master

**Comment by ashishiiit01** [comment]
I am getting the same issue  
**WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&watson-token=eyJraWQiO.......' **

**failed: HTTP Authentication failed; no valid credentials available**
_I am getting the token from the backend and at line var stream = reconizeMicrophone()_
There may be some error   npm watson-speech  module
`   import recognizeMicrophone from 'watson-speech/speech-to-text/recognize-microphone'

 onListenClick(){
      fetch('http://localhost:3002/api/speech-to-text/token')
          .then(function(response) {
              return response.text();
          }).then(function (token) {
              console.log('token is ',token)
              var stream = recognizeMicrophone({
                       
                token: token, 
                objectMode: true, 
                format: false
              });
              stream.on('data', function(data) {
                console.log(data);
              });
              stream.on('error', function(err) {
                  console.log(err);
              });
             
          }).catch(function(error) {
              console.log(error);
          }); `

**Comment by ashishiiit01** [comment]
@dpopp07 help  me to fix the above issue

**Comment by dpopp07** [comment]
@ashishiiit01 This looks like it may be a different issue. Are you using the [live examples](https://watson-speech.mybluemix.net/microphone-streaming.html) or writing your own code?

It looks like you're writing your own code. In your backend, is the service using IAM authentication? As in, are you using `username` and `password`, or `iam_apikey` for authentication? If you are using IAM, you need to use the parameter `access_token` instead of `token`. Let me know if this helps or not

**Comment by ashishiiit01** [comment]
@dpopp07  i dont have the username and password and i am using iam_apikey and i am also passing the url  which is given below 
![IMG_20190516_112819](https://user-images.githubusercontent.com/46279217/57830006-613f0880-77ce-11e9-8622-97e4a6680deb.png)

Also i am following the [live example](https://watson-speech.mybluemix.net/microphone-streaming.html) 
i have also tried with access_token instead of token

I am using  backend which is given below and live example code only. but **error** is coming **browser.js:16 WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&access_token=ABCDEFG' failed: HTTP Authentication failed; no valid credentials available
W3CWebSocket @ browser.js:16
RecognizeStream.initialize @ recognize-stream.js:176
RecognizeStream._write @ recognize-stream.js:342
doWrite @ _stream_writable.js:405
writeOrBuffer @ _stream_writable.js:394
Writable.write @ _stream_writable.js:303
ondata @ _stream_readable.js:662
EventEmitter.emit @ events.js:81
addChunk @ _stream_readable.js:297
readableAddChunk @ _stream_readable.js:279
Readable.push @ _stream_readable.js:240
Transform.push @ _stream_transform.js:139
WebAudioL16Stream.transformAudioBuffer @ webaudio-l16-stream.js:187
handleFirstAudioBuffer @ webaudio-l16-stream.js:172
Transform._read @ _stream_transform.js:177
Transform._write @ _stream_transform.js:164
doWrite @ _stream_writable.js:405
writeOrBuffer @ _stream_writable.js:394
Writable.write @ _stream_writable.js:303
ondata @ _stream_readable.js:662
EventEmitter.emit @ events.js:81
addChunk @ _stream_readable.js:297
readableAddChunk @ _stream_readable.js:279
Readable.push @ _stream_readable.js:240
recorderProcess @ microphone-stream.js:56
App.js:25 Error: WebSocket connection error: WebSocket connection error
    at WebSocket.socket.onerror (recognize-stream.js:189)**
`

'use strict';

const express = require('express');
const app = express();
const AuthorizationV1 = require('watson-developer-cloud/authorization/v1');
const SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1');
const TextToSpeechV1 = require('watson-developer-cloud/text-to-speech/v1');
const vcapServices = require('vcap_services');
const cors = require('cors')


// on bluemix, enable rate-limiting and force https
if (process.env.VCAP_SERVICES) {
  // enable rate-limiting
  const RateLimit = require('express-rate-limit');
  app.enable('trust proxy'); // required to work properly behind Bluemix's reverse proxy

  const limiter = new RateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 100, // limit each IP to 100 requests per windowMs
    delayMs: 0 // disable delaying - full speed until the max limit is reached
  });

  //  apply to /api/*
  app.use('/api/', limiter);

  // force https - microphone access requires https in Chrome and possibly other browsers
  // (*.mybluemix.net domains all have built-in https support)
  const secure = require('express-secure-only');
  app.use(secure());
}

app.use(express.static(__dirname + '/static'));
app.use(cors())

// speech to text token endpoint
var sttAuthService = new AuthorizationV1(
  Object.assign(
    {
    
      iam_apikey:'api key provided in the screenshot', // if using an RC service
      url:'https://gateway-wdc.watsonplatform.net/speech-to-text/api'

    },
    vcapServices.getCredentials('speech_to_text') otherwise returns {}
  )
);
app.use('/api/speech-to-text/token', function(req, res) {
  sttAuthService.getToken(function(err, token) {
    if (err) {
      console.log('Error retrieving token: ', err);
      res.status(500).send('Error retrieving token');
      return;
    }
    res.send(token);
  });
});

const port = process.env.PORT || process.env.VCAP_APP_PORT || 3002; 
app.listen(port, function() {
  console.log('Example IBM Watson Speech JS SDK client app & token server live at http://localhost:%s/', port);
});

// Chrome requires https to access the user's microphone unless it's a localhost url so

if (!process.env.VCAP_SERVICES) {
  const fs = require('fs');
  const https = require('https');
  const HTTPS_PORT = 3001;

  const options = {
    key: fs.readFileSync(__dirname + '/keys/localhost.pem'),
    cert: fs.readFileSync(__dirname + '/keys/localhost.cert')
  };
  https.createServer(options, app).listen(HTTPS_PORT, function() {
    console.log('Secure server live at https://localhost:%s/', HTTPS_PORT);
  });
}`

**Comment by Cr0up13r** [comment]
Any progress here? I'm having the same issue running the live examples on http://localhost:3000

**Comment by Cr0up13r** [comment]
Unfortunately the issue described by **ashishiiit01** still exists

![image](https://user-images.githubusercontent.com/7265297/58312049-cae09780-7e0a-11e9-8682-5e0313852c88.png)

**Comment by ashishiiit01** [comment]
@Cr0up13r @dpopp07 
i have solved this issue in my local machine. There is a problem in **npm watson-speech module** . In npm module  **node_modules/watson-speech/speech-to-text** file , there is url **_wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize_** for the particular region 
So to fix it , U have to give dynamic url for that region.

**To Fix in local Machine**
Go To **node_modules/watson-speech/speech-to-text** file and change the url to particular region which is given in your credentials  in ibm speech-to-text   service

**Comment by jeffsbaker** [comment]
> @ashishiiit01 This looks like it may be a different issue. Are you using the [live examples](https://watson-speech.mybluemix.net/microphone-streaming.html) or writing your own code?
> 
> It looks like you're writing your own code. In your backend, is the service using IAM authentication? As in, are you using `username` and `password`, or `iam_apikey` for authentication? If you are using IAM, you need to use the parameter `access_token` instead of `token`. Let me know if this helps or not

Previously, everything worked using username and password. But now IBM cloud is forcing me to use IAM tokens. So I used the suggestion here and changed the "token" key to "access_token". So previously the code was:
`stream = WatsonSpeech.SpeechToText.recognizeMicrophone({
	        token: token,`
Now the code is:
`stream = WatsonSpeech.SpeechToText.recognizeMicrophone({
	        access_token: token,`

I also had to download the new watson-speech.min.js for it to work. Now it gives this error one time in developer console:

> browser.js:16 WebSocket connection to 'wss://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_BroadbandModel&access_token=no-token' failed: HTTP Authentication failed; no valid credentials available

But despite the error it is working now in displaying the speech to text.

**Comment by biknandy** [comment]
Did anyone find a current solution to this problem?

**Comment by ywsong2** [comment]
For Javascript, I had same issue and fixed it. Here are steps.

1. Get access_token using apikey from https://iam.cloud.ibm.com/identity/token. I used PHP cURL. This will give 'access_token'. Reference: https://cloud.ibm.com/docs/iam?topic=iam-iamtoken_from_apikey

2. For me, I used WatsonSpeech.SpeechToText.recognizeFile() function. You need to change several things here. First, you can use access token you got from IAM and put the key name as 'accessToken' (not access_token). You can find your region from here (https://cloud.ibm.com/docs/services/speech-to-text?topic=speech-to-text-websockets). You can find your instance ID at IBM resource page. 

Example:
```
WatsonSpeech.SpeechToText.recognizeFile({
                accessToken: '{your access token from IAM}',
                url: 'https://api.{your region}.speech-to-text.watson.cloud.ibm.com/instances/{your instance id}',
                file: audioURL,
                resultsBySpeaker: false,
                outputElement: outputTextBox,
                timestamps: true,
                play: false
            })
```
Then, it worked for me.
