### ISSUE TITLE
stop() method not working

### ISSUE THREAD

**Issue by jeffsbaker** [watson-developer-cloud/speech-javascript-sdk#136]
Version 0.36.2

Actual Behavior: If stream = WatsonSpeech.SpeechToText.recognizeMicrophone(...) is accidentally called twice as through a button click and then stream.stop() is called the speech to text continues to operate. Even if you keep calling stream.stop() then it continues to transcribe. The stop event is emitted but it never really stops.

Expected Behavior: For stream.stop() to stop the transcribing of speech from the microphone even if stream = WatsonSpeech.SpeechToText.recognizeMicrophone(...) is called twice.

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved.

**Comment by jeffsbaker** [comment]
> Thanks a lot for filing this issue! Would you like to write a PR for this? I'd be more than happy to walk you through the steps involved.

Are you able to write the PR?

**Comment by germanattanasio** [comment]
I was asking that to you @jeffsbaker. I don't have time to look into this. Maybe you had an idea on what the problem was

**Comment by jeffsbaker** [comment]
I don't know why it is doing it. So I'm not sure how to go about doing a Pull Request. All I can do is provide the same information.

**Comment by w0o** [comment]
@jeffsbaker seems like a strange pattern to be calling recognizeMicrophone twice due to a button click. It can cause multiple issues such as creating duplicate handlers and streams and more and this should not be a valid pattern of working with the library as you should be expecting only one stream per microphone. 
I would suggest you workaround this by having a conditional that will avoid calling recognizeMicrophone twice within your click handler.

@germanattanasio Unless you see a valid reason for calling recognizeMicrophone twice I suggest to close this issue.
