### ISSUE TITLE
is stream bifurcation possible?

### ISSUE THREAD

**Issue by mreinstein** [watson-developer-cloud/speech-javascript-sdk#26]
My app transcribes audio, but also does a bunch of other processing on the side (sentiment analysis, etc.) I want the speech-to-text to display as quickly as possible in the app, but I also want to save the raw audio on my server for analysis which happens later.

I was thinking maybe this could be done by getting at the underlying mediaStream used by this sdk, and send the audio data in parallel to my backend. Is this possible?

thanks for a great library!

**Comment by nfriedly** [comment]
Yes, you can do that. 

At the moment, the source audio stream is not available when you use the `recognizeMicrophone()` or `recognizeFile()` helper methods, but all they are is helpers. You can copy the source (e.g. https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js) into your own app, and then save a copy of the raw audio by either `pipe()`'ing it or else listening for the `data` events.

You'll want to add your code around https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L145 - there are two streams to choose from, depending on the format you want:

* `micStream` if you want the original Web Audio-formatted [AudioBuffers](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer) (32-bit floats, either 44.1khz or 48khz)
* `l16Stream` if you want the "raw WAV" formatted [Buffers](https://nodejs.org/api/buffer.html) that we send to the Watson service (16-bit int's, 16khz)

It's also possible to pull Node.js style Buffers out of micStream that maintain the original quality and rate if you tweak the settings.

As an alternative to copying the helper code, you can send me a PR to expose those streams similar to https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L190 - note that it will be a little more complex than that, because you have to wait on a promise to resolve before the streams are created.  It should be possible to create the L16Stream and expose it synchronously, and then just pipe to it later when the micStream is ready, if that's the one you want.

**Comment by mreinstein** [comment]
> You can copy the source (e.g. speech-to-text/recognize-microphone.js) into your own app
> and then save a copy of the raw audio by either `pipe()`'ing it or else listening for the data events.

so if i understand, you're saying use `recognize-microphone.js` as a high-level template, make my own copy and then hook up any additional stream handling to pipe the audio somewhere (my own servers) ?

btw I'm impressed with how clean the design is for this repo. I was expecting a nightmare when I first started peering at the source, and it's a pleasant surprise to see how thought-through it is. :)

**Comment by nfriedly** [comment]
> so if i understand, you're saying use recognize-microphone.js as a high-level template, make my own copy and then hook up any additional stream handling to pipe the audio somewhere (my own servers) ?

Yep, exactly. And, of course, feel free to delete any bits you don't need.

> btw I'm impressed with how clean the design is for this repo. I was expecting a nightmare when I first started peering at the source, and it's a pleasant surprise to see how thought-through it is. :)

Thanks!

**Comment by mreinstein** [comment]
@nfriedly does this look like a reasonable approach to modifying the API?

https://github.com/mreinstein/speech-javascript-sdk/commit/31204d5a4d3f6671c0df4614c8511e38cd85aa02

with the above modification, can adjust the call to `recognizeMicrophone()` like this:

```javascript
fetch('/api/speech-to-text/token')
  .then(function(response) {
      return response.text();
  }).then(function (token) {

    var stream = WatsonSpeech.SpeechToText.recognizeMicrophone({
        token: token,
        outputElement: '#output', // CSS selector or DOM Element
        mediaStreamCallback: function(err, stream) {
          // TODO: you can now hook up the media stream to other stuff here...
          //             drawing a waveform, uploading audio to a backend, etc.
        }
    });
```

I realize this is very rough at the moment (very little error checking, no docs, etc.) but if this seems like a reasonable approach, happy to follow up with a PR that polishes appropriately.

thanks!

**Comment by nfriedly** [comment]
@mreinstein That looks perfectly fine for your use case. 

I'd ask for some changes for a PR, though:
* Use Promises rather than callbacks for the public API
* Add JSDoc for the parameter
* It should expose all streams rather than just this one 
  (I know that's a bit hypocritical given that it already exposes the recognizeStream, but that's essentially an undocumented hack for the [demo app's](https://speech-to-text-demo.mybluemix.net/) JSON tab. This would be making it part of the official API.)
* `recognizeFile()` should have an equivalent API
* There should be tests that checks for basic functionality on both recognizeMicrophone and recognizeFile - either part of the end-to-end suite, or else a new with mocks for all of the underlying streams

**Comment by mreinstein** [comment]
@nfriedly 

> Use Promises rather than callbacks for the public API

Correct me if I'm mistaken... I'm under the impression that Promises are appropriate when you have an event that fires exactly 1 time, and callbacks are appropriate when you have an event that fires 0 or more times. given this code:

```javascript
var stream = recognizeMicrophone({
  token: token,
  outputElement: '#output', // CSS selector or DOM Element
  mediaStreamCallback: function(err, stream) {
     console.log('yes this definitely fired')
     // do something with the media stream here
  }
})
```

If I transcribe twice, `yes this is definitely fired` will show up twice in the logs. As it should, because I'm not keeping the microphone, and a separate userMediaStream object is generated each time.

thoughts?

**Comment by nfriedly** [comment]
What I had in mind was something like this for the public API:

```js
var stream = recognizeMicrophone({
  token: token,
  outputElement: '#output', // CSS selector or DOM Element
});
stream.getStreams().then(function(streams) {
     console.log('yes this definitely fired')
     // do something with streams.microphoneStream here
});
```

In that case, it would still log `yes this definitely fired` to the console twice if you ran that code twice.

Internally, it already creates a new `getMicStream` promise each time you call `recognizeMicrophone()`, so what I'm imagining is that https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L140 changes from

```js
 getMicStream.then(function(micStream) {
```
to
```js
var streamsPromise =  getMicStream.then(function(micStream) {
```
and then we make sure it returns the (now-completed) streams array on https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js#L174
```js
   return streams;
```

and then somewhere around the end of `recognizeMicrophone()`, we'd define the public API like so:

```js
stream.getStreams = function() {
  return streams.then(function(streamsArr) {
      var streamsObj = {};
      streamsArr.forEach(function(s) {
        // maybe lower case the first letter.. or just skip this and return an array
        streamsObj[s.constructor.name] = s; 
      });
      return streamsObj;
  });
};
```

Although, to be honest, the more I think about it, the less I like this idea. It seems like an awful lot of complexity being added to the "easy mode" to support relatively advanced usage.

**Comment by mreinstein** [comment]
> Internally, it already creates a new getMicStream promise each time you call 

Yes. Sorry. I misread the logic in the `recognize-microphone`. In actuality this would return exactly once for each event, and a promise could be used.


> the more I think about it, the less I like this idea. 
> It seems like an awful lot of complexity being added to the "easy mode" 
> to support relatively advanced usage.

I agree. The structure of this module does not currently lend itself to getting at one of the streams that is in the middle of this pipeline. It feels messy to bolt this on.

While we're on the subject of complexity..one thing I've noticed is the amount of javascript that gets generated in the browserify process. I think what happens is using node's stream constructs ends up pulling in some very heavy browser shims.  

I'm torn because on one hand, I love the elegance of using node-style streams for doing these operations, but the code that actually downsamples to 16k, sends things over the websockets...it's like 1/10th the size of that (16k vs 160k)

Have you given thoughts to coming up with an extremely streamlined browser module that might forego some of the elegance in favor of tiny code footprint?

**Comment by nfriedly** [comment]
> the amount of javascript that gets generated in the browserify process

Yea.. smaller file size would be good. I ran it through [disc](https://www.npmjs.com/package/disc) a while back to look for low hanging fruit; I should probably do that again soon. But ultimately you're right, building on top of Node.js streams does add a fair bit of overhead.

The [old demo](https://github.com/watson-developer-cloud/speech-to-text-nodejs/tree/v1) that the downsampling and other code came from didn't have any dependencies, and the js was smaller, but it was just crazy complex and scarred a lot of people away. (It also had a lot of jQuery/UI code in the non-UI parts, and a WebWorker, and a canvas, and a lot of other stuff...)

One of my goals is for this library is to be able to share code with the Node.js SDK, so that kind of boxes me into this path.

Ultimately, it's all open source, though, so if someone wants to create a timed down no-streams version, that's totally fine. I just don't think *I'll* do it very soon.

**Comment by mreinstein** [comment]
@nfriedly mulling over this more, I have an alternative refactor idea, which I think is cleaner:

How about in the constructor it could take in an optional mediaStream which has already been acquired? If present it would not attempt to acquire one inside `recognizeMicrophone`. That would enable me to get at the mediaStream object and hook up my own stuff to it, without impacting the API that `recordStream` exposes.

**Comment by nfriedly** [comment]
Oh, yea, I like that a lot better. Good thinking.

**Comment by mreinstein** [comment]
@nfriedly here's an initial attempt at this. Happy to add more details, etc. if this looks like a reasonable approach

https://github.com/watson-developer-cloud/speech-javascript-sdk/pull/27

**Comment by vjkholiya123** [comment]
In our application, we are using IBM STT service which is being done through WebSocket connection made from the front end part i.e ReactJS. But due to change in the IBM policies we can no longer do so. Also we are using "recognizeMicrophone" module in React to create web socket connection and get the data from the response.
With this module i.e recognizeMicrophone we are providing option values like access_token, model, speaker_labels, and so on.
Since, from the updated IBM services we cannot be able to use WebSocket connection from browser which made our application run in failure. Is there any alternative or solution to recognizeMicrophone that sets up the microphone, and does all other things same as recognizeMicrophone but without Websocket connection. We will make WebSocket connection in our back end part. 
Any solution for our problem?

**Comment by germanattanasio** [comment]
You can use the library from the browser @vjkholiya123 you just need to get a token. You can use the apikey from IAM
