### ISSUE TITLE
Custom model support in javascript sdk

### ISSUE THREAD

**Issue by nirmalsinghania2008** [watson-developer-cloud/speech-javascript-sdk#32]
i am using the application https://audio-analysis-starter-kit.mybluemix.net.
I was trying to use custom speech to text models created by me having specific customization id.

The application is using RecognizeElement for transcribing youtube video to text.
After looking at the reference and source code,i came to know that customization_id support is not there in RecognizeElement or rather any function in javascript sdk(RecognizeMicrophone,RecognizeFile etc)

So, i used nodejs sdk's RecognizeStream function which accepts customization_id,after converting video to audio on server side using ffmpeg.

but i am having some performance issues as i have to send "data" events continuously from backend to frontend.(i am using ajax long polling)
and server sent events are not working in my case as registering "EventSource" calls my recognize route which i don't want.

Is there any plan to add support for custom models in  speech javascript sdk ?

**Comment by gusdaud** [comment]
I'd love to have that too!

**Comment by nfriedly** [comment]
The `customization_id` is supported on current releases of the SDK, however RecognizeElement support was removed due to quality issues. It now lives in an [example](https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples/static/audio-video-deprecated) which you're welcome to use, but just won't be supported officially.

However, your server-side conversion may be the best option ultimately, especially if you can generate [WebVVT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API) format subtitles that browsers natively understand.
