### ISSUE TITLE
Unable to get all of transcribed audio when using push-to-talk approach

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/speech-javascript-sdk#58]
Basically what I am trying to do is build a walkie-talkie type of chatbot.

When the user is holding down a button, audio should be transcribed and when they lift up on the button, the complete transcription should be sent to a server to be processed.  I want all the audio sent while the button was held down to be transcribed, so I can't send the transcription at the point of the button lift up (which might be missing the last word or syllable).  The transcription should be sent after of all the audio has been transcribed.  I see no way to do this because there isn't an "all-audio-transcribed" type of event.

Basically if you take the example [https://watson-speech.mybluemix.net/microphone-streaming.html](https://watson-speech.mybluemix.net/microphone-streaming.html) and change the following:

1. make it a single button labeled "push-to-talk"
2. add another div with id "outputSent" that represents what is sent to a server
3. mousedown event starts the stream of audio to STT
4. mouseup event stops the streaming of audio
5. when transcription is finished, update #outputSent

I think something needs to be added to the API for # 5 to work.

I think using a STT service in Frankfurt will help demonstrate this problem so that transcription takes a little longer after the user lifts up on the button.

/cc @nfriedly

**Comment by nfriedly** [comment]
Note to self: the bug is that RecognizeStream immediately sends the stop command when stop is triggered, but there may be some buffered audio that never gets sent. This will be worse with short bursts and/or slower connections.

`.stop()` should default to a "graceful" stop where only the microphone is stopped, and the RecognizeStream is allowed to close automatically once all audio has been sent. It should probably also support a "hard" stop where audio upload is immediately stopped.

**Comment by troyibm** [comment]
The other SDKs have a "final" boolean that indicates the transcription is complete for that sentence.

**Comment by germanattanasio** [comment]
Maybe a `.stop({force: true})`
