### ISSUE TITLE
iOS 11 Microphone capture not working.

### ISSUE THREAD

**Issue by LiamChapman** [watson-developer-cloud/speech-javascript-sdk#61]
Hi there,

I've been playing with the SDK for a few weeks now and I've been unable to get the Microphone to work on iOS11, which has recently included getUserMedia and WebRTC support.

At first I thought it was a bug with iOS, but I did some tests outside of the SDK, i've been able to get the mic to work. But with the SDK it fails silently. 
 
Works on iOS 11:
https://youennf.github.io/webrtc-tests/src/content/getusermedia/audio/ 

Does not work on iOS 11:
https://watson-speech.mybluemix.net/microphone-streaming.html 

It might something todo with the get-user-media-promise dependency.

- Steps to reproduce:
Use links above

- Expected behaviour:
Microphone to transcribe audio or at least some audio response / echo.

- Actual behaviour:
No error or response on iOS 11 or in console via Safari. Demo does not work.

- Browser version(s)
iOS 11 Safari

- SDK version:
0.34.1

Thanks,

Liam

**Comment by nfriedly** [comment]
iOS (and, I think Chrome on Android now) only allow audio to work in direct response to a user action. 

https://watson-speech.mybluemix.net/microphone-streaming.html won't work because it fetches the token first and then starts recording after the token loads, so it doesn't count as a *direct* response to a user action.

https://watson-speech.mybluemix.net/microphone-streaming-preload-token.html works, though, because it pre-loads the token.

With a pre-loaded token, you just need to be aware that the tokens expire after an hour, so you'll need to periodically refresh it if you expect the page to be open for a longer timeframe.

**Comment by poojarfuturistic5** [comment]
hello I am using wzrecorder but it's not showing waveforms only recording the audio
