### ISSUE TITLE
downsampling algorithm used?

### ISSUE THREAD

**Issue by darkyen** [watson-developer-cloud/speech-javascript-sdk#8]
Can you link the downsampling algorithm used?

**Comment by nfriedly** [comment]
@daniel-bolanos wrote that, I just imported it from the current STT demo app. Dani, can you provide any details here?

**Comment by daniel-bolanos** [comment]
We are just applying a filter to the signal. We apply a window to the samples, from left to right, and then apply the filter. It is pretty efficient and it carries over samples across buffers, so it might be slightly better than the filter provided by WebAudio. I noticed that the WebAudio filter was not available in older browsers so we dicided to stick to our downsampling. But in the long term the native downsamplings seems like a better idea since it is more readable and easier to maintain.

**Comment by darkyen** [comment]
I am trying to upsample the resultant stream on server. Any pointers?

**Comment by daniel-bolanos** [comment]
I'm glad the implementation is useful to you. Why do you need upsampling?

**Comment by darkyen** [comment]
@daniel-bolanos Need to mix it with another audio stream, I intend to use libresample later on server and more C++ land code for mixing audio. But for now most of that code is in JavaScript for rapid prototyping

**Comment by daniel-bolanos** [comment]
we got the inspiration from matlab, I think our filter is a version of one filter we found there, but shorter. If I remember correctly. Please take a look at matlab's manual...

**Comment by darkyen** [comment]
Thanks :-), just finished up sampling :+1:
